spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(LPramCL/Stywm0mLuO2Tx94BONYQf3VRCXsAwJlowXI+GtQ5TDQHJGTFv9Fa5X5rMJmehQq5XI9z0t3FsR/+/E2vG3Rwgx+UclLIIGtyLZv4tNrle65haXcBCLlYfZ7k)
            client-secret: ENC(aftbK0k57QfOAo/VYLd3aM0ethOdXmwPCzHT+ffSPEhfYDvbtbsWyZw68ckqXLoydce9atYj1wI4wfx6ipQbRQ==)
            scope:
              - email
              - profile
              # - openid # OIDC 인증 활성화

app:
  oauth2-redirect-uri: http://localhost:3000/oauth2/redirect

---
spring:
  config:
    activate:
      on-profile:
        - dev

app:
  oauth2-redirect-uri: https://meme.megabrain.kr/oauth2/redirect

---
spring:
  config:
    activate:
      on-profile:
        - prod

app:
  oauth2-redirect-uri: https://meme.megabrain.kr/oauth2/redirect
