spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(d1ChCGaDF2tGMjE002rXx+qdF2oVprEI60fSQd3wLfz2ErukVrI+ag8n61Owpzc89+MBT3SbVFALIPCdiclhVJVYwlpAYzCCFNE8sMjXUfw/jeLfz1JVmsQH4k1oe2eS)
            client-secret: ENC(4Yo4HEnBdqTyKuxuDGD8bp6DKX7ErZ72i7jbw3j8MSI7OrRVPKc9o6ffYwtByrMCyK/zJTqWJvEu6YhfiUv2Vw==)
            scope:
              - email
              - profile
              # - openid # OIDC 인증 활성화

app:
  oauth2-redirect-uri: http://localhost:3000/oauth2/redirect

---
spring:
  config:
    activate:
      on-profile:
        - dev

app:
  oauth2-redirect-uri: http://localhost:3000/oauth2/redirect

---
spring:
  config:
    activate:
      on-profile:
        - prod

app:
  oauth2-redirect-uri: http://localhost:3000/oauth2/redirect
