spring:
  profiles:
    active: default
    include:
      - mysql
      - redis
      - jwt
      - flyway
      - oauth
      - jasypt

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    com.example : DEBUG

uploadPath: file:./images/